prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1

grafana:
  enabled: true
  adminPassword: admin
  service:
    type: LoadBalancer

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true
