apiVersion: v2
name: restaurant-finder
description: A Helm chart for deploying the Restaurant Finder application on Kubernetes.
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: ofer
    email: zadaka.ofer@gmail.com
sources:
  - https://github.com/Oferzz/restaurants-finder
keywords:
  - restaurant
  - finder
  - helm
  - kubernetes
home: https://github.com/Oferzz/restaurants-finder
icon: https://example.com/icon.png
