name: Kubernetes Deployment

on:
  push:
    paths:
      - 'k8s/**'
      - '.github/workflows/deploy-to-k8s.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        sudo apt-get update && sudo apt-get install -y awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Update kubeconfig for EKS
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name retaurant-finder-cluster
    
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy using Helm
      run: |
        helm upgrade --install restaurant-finder ./k8s/helm/restaurant-finder \
          --namespace restaurant-finder \
          --create-namespace \
          --set serviceAccount.name=restaurant-finder-sa \
          --set serviceAccount.roleArn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/restaurants-finder-eks-cluster-irsa \
          --set image.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }} \
          --set image.tag=${{ github.sha }} \
          --set adminPassword=${{ secrets.ADMIN_PASSWORD }}